FROM ubuntu:latest
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install openjdk-8-jdk wget git maven
RUN mkdir /usr/local/tomcat
RUN wget http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.43/bin/apache-tomcat-8.5.43.tar.gz -O /tmp/tomcat.tar.gz
RUN cd /tmp && tar xvfz tomcat.tar.gz
RUN cp -Rv /tmp/apache-tomcat-8.5.43/* /usr/local/tomcat/
## RUN git clone https://github.com/Srini544/warfile.git
## RUN cp warfile/gst.war /usr/local/tomcat/webapps
RUN git clone https://github.com/Srini544/MyMavenCode.git
RUN cd MyMavenCode
RUN mvn clean package
RUN cp target/*.war /usr/local/tomcat/webapps
EXPOSE 8080
CMD /usr/local/tomcat/bin/catalina.sh run
